# Generated by Django 4.1 on 2022-08-21 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='product.collection'),
            preserve_default=False,
        ),
    ]
